# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(username: "example1", password_digest: "example1", name: "example1", address: "example1")
# User.create(username: "example2", password_digest: "example2", name: "example2", address: "example2")
# User.create(username: "example3", password_digest: "example3", name: "example3", address: "example3")
# User.create(username: "example4", password_digest: "example4", name: "example4", address: "example4")
# User.create(username: "example5", password_digest: "example5", name: "example5", address: "example5")
# User.create(username: "example6", password_digest: "example6", name: "example6", address: "example6")


# Item.destroy_all

# Item.item_by_category("561-562") ## ""Bread, Packaged"
# Item.item_by_category("561-563") ## ""Stuffing, Pitas, Flatbreads, Wraps & Pizza Shells""
# Item.item_by_category("917-920") ## "Cave-Ripened Cheese"
# Item.item_by_category("917-921") ## "Feta Cheese"
# Item.item_by_category("6940-716")  # Beef
# Item.item_by_category("6940-717")  # Pork
# Item.item_by_category("7221-851")  # Crab and Lobster
# Item.item_by_category("7221-853")  # Frozen Shrimp & Seafood

# 5.times do
#     FavoriteRecipe.create(user_id: User.first.id, name: Faker::Commerce.product_name)
# end

# Fridge.create(user_id: User.first.id)

# 20.times do
#     FridgeItem.create(item_id: Item.all.sample.id, fridge_id: Fridge.first.id)
# end

# 5.times do
#     CartItem.create(item_id: Item.all.sample.id, cart_id: Cart.first.id)
# end



# Recipe.create(user_id: User.last.id, title: "Oxtail Stew", ingredients: "cooking oil , oxtail, onion, garlic, thyme, smoked paprika, tomato paste, whole Scotch bonnet pepper or habanero, green onions, allspice, Worcestershire sauce, curry powder, canned butter beans, bouillon, salt", picture: "https://www.africanbites.com/wp-content/uploads/2015/11/IMG_6452.jpg", source_url: "https://www.africanbites.com/jamaican-oxtail-stew-2/")
# Recipe.create(user_id: User.last.id, title: "Lemon Parmesan Pasta With Shrimp", ingredients: "Linguine Pasta, Garlic, Red Pepper Flakes, Shrimp, Italian Seasoning, Parmesan Cheese, Lemon Juice", picture: "https://therecipecritic.com/wp-content/uploads/2016/08/lemongarlicparmesamshrimppasta4.jpg", source_url: "https://therecipecritic.com/lemon-garlic-parmesan-shrimp-pasta/")
# Recipe.create(user_id: User.last.id, title: "Kimchi Jigae", ingredients: "Pork Belly, Onion, Kimchi, Garlic, Ginger, Shaoxing Wine, Gochujang, White Miso, Soy Sauce, Gochugaru, Silken Tofu, Scallions, Butter ", picture: "https://www.seriouseats.com/recipes/images/20101103_dt_kimchijigae.jpg", source_url: "https://www.seriouseats.com/recipes/2010/11/kimhi-jigae-kimchi-soup-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Tonkatsu Ramen", ingredients: "Pork Trotters, Onions, Garlic, Leek, Ginger, Scallions, Dried Shitake Mushrooms, Pork Fatback ", picture: "https://www.seriouseats.com/recipes/images/2012/02/20120227-tonkotsu-ramen-broth-pork-fat-26.jpg", source_url: "https://www.seriouseats.com/recipes/2012/02/rich-and-creamy-tonkotsu-ramen-broth-from-scratch-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Spicy Jerk Chicken", ingredients: "Scotch Bonnet, Scallion, Ginger, Garlic, Thyme, Allspice, Nutmeg, Dark Brown Sugar, Soy Sauce, Limes, Whole Chicken, Allspice Berries, Bay leaves ", picture: "https://www.seriouseats.com/recipes/images/2013/07/20130715-jerk-chicken-final-food-lab-38.jpg", source_url: "https://www.seriouseats.com/recipes/2013/08/jerk-chicken.html")
# Recipe.create(user_id: User.last.id, title: "Miso Black Cod", ingredients: "Sake, Mirin, White Miso, Sugar, Black Cod fillet", picture: "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_803/k%2Farchive%2F3931a592af8ade154bf5357f733ba57fbd54ba51", source_url: "https://www.thekitchn.com/recipe-nobu-miso-marinated-black-cod-117238")
# Recipe.create(user_id: User.last.id, title: "Indian Butter Chicken", ingredients: "Shallot, White Onion, Butter, Lemon Juice, Garam Masala, Chili Powder, Ground Cumin, Bay Leaf, Tomato Puree, Cayenne, Peanut Oil, Ghee, Tomato Paste", picture: "https://cafedelites.com/wp-content/uploads/2019/01/Butter-Chicken-IMAGE-64.jpg", source_url: "https://www.allrecipes.com/recipe/45957/chicken-makhani-indian-butter-chicken/")
# Recipe.create(user_id: User.last.id, title: "Chili", ingredients: "Kidney Beans, Dark Chocolate, Yellow Onion, Thai Chili Peppers, Garlic, Dried Oregano, Bay Leaf, Crushed Tomato, Cider Vinegar, Bourbon, Ancho Chili, Costeno, Arbol Chili, Short Ribs, Chicken Stock, Tomato Paste, Coriander, Cumin, Coffee",  picture: "https://www.seriouseats.com/recipes/images/2017/09/201001-ultimate-chili-kenji-lopez-alt.jpg", source_url: "https://www.seriouseats.com/recipes/2010/01/the-best-chili-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Shepherd's Pie", ingredients: "Russet Potato, Butter, Celery, Garlic, Tomato Paste, Red Wine, Thyme, Bay Leaf, Worcestershire, Chicken Stock, Ground Lamb, Yellow Onion, Carrot",  picture: "https://www.seriouseats.com/recipes/images/2016/10/20161012-shepherds-pie-vicky-wasik-Version-A-21.jpg", source_url: "https://www.seriouseats.com/recipes/2016/10/shepherds-pie-beef-lamb-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Chicken Pot Pie", ingredients: "Chicken Stock, Whole Chicken, Onion, Carrots, Celery, Garlic, Thyme, Parsley, White Wine, Frozen Peas, Flour, Puff Pastry", picture: "https://www.seriouseats.com/images/2017/09/20170902-chicken-pot-pie-vicky-wasik33.jpg", source_url: "https://www.seriouseats.com/2017/09/how-to-make-chicken-pot-pie.html")
# Recipe.create(user_id: User.last.id, title: "Chinese Eggs and Tomato", ingredients: "Tomato, Scallion, Eggs, White Pepper, Sesame Oil, Shaoxing Wine, Sugar", picture: "https://thewoksoflife.com/wp-content/uploads/2019/05/tomato-egg-11.jpg", source_url: "https://thewoksoflife.com/stir-fried-tomato-and-egg/")
# Recipe.create(user_id: User.last.id, title: "Oven Baked Carnitas", ingredients: "Onions, Cilantro, Pork Shoulder, Orange, Garlic, Bay Leaf, Cinnamon, Tomatillos, Jalapeno, Limes, Feta, Corn Tortillas",  picture: "https://www.seriouseats.com/recipes/images/2016/06/20100729-carnitas-09.jpg", source_url: "https://www.seriouseats.com/recipes/2010/07/no-waste-tacos-de-carnitas-with-salsa-verde-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Extra-Crisp Roasted Potatoes", ingredients: "Baking Soda, Garlic, Parsley, Duck Fat, Yukon Gold Potatoes", picture: "https://www.cookingclassy.com/wp-content/uploads/2020/05/lemon-roasted-potatoes-8-600x900.jpg", source_url: "https://www.seriouseats.com/recipes/2016/12/the-best-roast-potatoes-ever-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Ramen Chashu", ingredients: "Soy Sauce, Sake, Mirin, Sugar, Scallions, Garlic, Ginger, Shallot", picture: "https://www.seriouseats.com/recipes/images/2012/03/20120301-tonkotsu-chashu-cha-siu-pork-belly-ramen-08.jpg", source_url: "https://www.seriouseats.com/recipes/2012/03/chashu-pork-marinated-braised-pork-belly-for-tonkotsu-ramen-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Chaliapin Steak Don", ingredients: "Beef Sirloin, Onion, Garlic, Pepper, Potato Starch, Umeboshi Paste, Pickled Plum, Soy Sauce, Red Wine, butter", picture: "https://vignette.wikia.nocookie.net/shokugekinosoma/images/1/1e/Chaliapin_Steak_Don_%28anime%29.png/revision/latest?cb=20150515215831", source_url: "https://shokugekinosoma.fandom.com/wiki/Chaliapin_Steak_Don")
# Recipe.create(user_id: User.last.id, title: "Eggs Benedict", ingredients: "Canadian Ham, Eggs, English Muffins, Hollandaise, Chives, Apple Cider Vinegar",  picture: "https://www.simplyrecipes.com/wp-content/uploads/2010/04/eggs-benedict-vertical-a-1600-600x759.jpg", source_url: "https://www.seriouseats.com/recipes/2014/06/food-lab-foolproof-eggs-benedict-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Khao Suey", ingredients: "Sesame Oil, Onion, Garlic, Ginger, Tumeric Powder, Chicken Thighs, Chicken broth, Coconut Milk, Fish Sauce, Soy Sauce, Angel Hair Pasta, Chickpea Flour, Lime Juice, Cilantro", picture: "https://www.paintthekitchenred.com/wp-content/uploads/2020/05/Instant-Pot-Khao-Suey-P1-Paint-the-Kitchen-Red-683x1024.webp", source_url: "https://www.paintthekitchenred.com/easy-instant-pot-khow-suey-burmese-noodles/")
# Recipe.create(user_id: User.last.id, title: "Pad See Ew", ingredients: "Flank Steak, Thai Black Soy Sauce, Corn Starch, Oyster Sauce, Sugar, Fish Sauce, White Pepper, Wide Rice Noodles, Garlic, Brocoli, Eggs", picture: "https://thewoksoflife.com/wp-content/uploads/2017/02/pad-see-ew-11.jpg", source_url: "https://thewoksoflife.com/pad-see-ew/")
# Recipe.create(user_id: User.last.id, title: "Pad Thai", ingredients: "Rice Noodles, Shrimp, Soy Sauce, Brown Sugar, Fish Sauce, Rice Vinegar, Eggs, Peanuts, Vegetables", picture: "https://www.cookingclassy.com/wp-content/uploads/2019/03/pad-thai-3-768x1152.jpg", source_url: "https://www.cookingclassy.com/chicken-pad-thai/")
# Recipe.create(user_id: User.last.id, title: "Mango Sticky Rice", ingredients: "White Rice, Coconut Milk, White Sugar, Tapioca Starch, Sesame Seeds, Mangos", picture: "https://www.seriouseats.com/recipes/images/2016/03/20160323-mango-sticky-rice-vicky-wasik-5.jpg", source_url: "https://www.allrecipes.com/recipe/150313/thai-sweet-sticky-rice-with-mango-khao-neeo-mamuang/")
# Recipe.create(user_id: User.last.id, title: "Bean Curd Szechuan Style", ingredients: "Tofu, Peanut Oil, Onion, Mushrooms, Cabbage, Bell Pepper, Szechuan Sauce, Scallions", picture: "https://www.feastingathome.com/wp-content/uploads/2019/03/Szechuan-Tofu-and-Veggies-105.jpg", source_url: "https://www.feastingathome.com/szechuan-tofu-and-veggies/")
# Recipe.create(user_id: User.last.id, title: "Mapo Tofu", ingredients: "Sichuan Peppercorn, Cornstarch, Silken Tofu, Ground Beef, Garlic, Ginger, Shaoxing wine, Chili Bean Paste, Chili Oil, Chicken Stock, Dark Soy Sauce, Scallions", picture: "https://www.seriouseats.com/recipes/images/20110711-mapo-dofu-primary.jpeg", source_url: "https://www.seriouseats.com/recipes/2011/07/real-deal-mapo-dofu-tofu-chinese-sichuan-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Sichuan Sliced Beef in Chili Sauce", ingredients: "Light Soy Sauce, Shaoxing Wine, Sugar, Dried Chili Peppers, Scallions", picture: "https://omnivorescookbook.com/wp-content/uploads/2018/04/1804_Fu-Qi-Fei-Pian_006.jpg", source_url: "https://omnivorescookbook.com/fu-qi-fei-pian/")
# Recipe.create(user_id: User.last.id, title: "Sushi Rice (Sumeshi)", ingredients: "Short Grain Sushi Rice, Konbu, Rice Wine Vinegar, Sugar", picture: "https://www.thespruceeats.com/thmb/Z2eQ4uqzcZwZsYK23-8slQoecbM=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/sushi-rice-recipe-2031498-hero-01-7c991045bced4354abb8fe57a3d4e1d7.jpg", source_url: "https://www.seriouseats.com/recipes/2010/07/sumeshi-vinegared-sushi-rice.html")
# Recipe.create(user_id: User.last.id, title: "Cabbage Pork Dumplings", ingredients: "All Purpose Flour, Napa Cabbage, Scallions, Fatty Ground Pork, Soy Sauce, Shaoxing Wine, Sugar", picture: "https://www.seriouseats.com/recipes/images/20110406-chinese-appetizers-dumplings-12.jpg", source_url: "https://www.seriouseats.com/recipes/2011/04/pork-and-leek-dumplings-with-homemade-wrapper.html")
# Recipe.create(user_id: User.last.id, title: "Homemade Pizza", ingredients: "Pizza Dough, San Marzano Tomatoes, Fresh Mozzarella, Parmesan cheese, Toppings",  picture: "https://www.seriouseats.com/images/2017/02/20170213-pizza-recipes-roundup-01.jpg", source_url: "https://www.seriouseats.com/2017/02/22-pizza-recipes.html")
# Recipe.create(user_id: User.last.id, title: "Spaghetti Pomodoro", ingredients: "Spaghetti, Onion, Olive Oil, Tomatoes, Red Pepper Flakes, Basil, Parmesan",  picture: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-190903-pasta-pomodoro-0201-landscape-pf-1568667704.jpg?crop=0.668xw:1.00xh;0.158xw,0&resize=768:*", source_url: "https://www.bonappetit.com/recipe/basically-spaghetti-pomodoro")
# Recipe.create(user_id: User.last.id, title: "Decadent Bolognese", ingredients: "Chicken Stock, Powedered Gelatin, San Marzano Tomatoes, Extra Virgin Olive Oil, Ground Beef Chuck 20% fat, Pork Shoulder, Lamb Shoulder, Carrots, Pancetta, Onions, Garlic, Whole Milk, Dry Wine, Heavy Cream, Bay Leaf, Fish Sauce", picture: "https://www.seriouseats.com/recipes/images/2014/12/20141204-slow-roasted-bolognese-01.jpg", source_url: "https://www.seriouseats.com/recipes/2014/12/the-best-slow-cooked-bolognese-sauce-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Buttermilk Fried Chicken", ingredients: "Paprika, Garlic Powder, Dried Oregano, Cayenne, Cornstarch, Baking Powder, Buttermilk, Chicken", picture: "https://www.seriouseats.com/recipes/images/2015/07/20150715-fried-chicken-21.jpg", source_url: "https://www.seriouseats.com/recipes/2015/07/the-food-lab-southern-fried-chicken-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Lumpia", ingredients: "Yellow Onion, Garlic, Carrot, Ginger, Ground Pork, Water Chestnut, Soy Sauce, Scallion, Cilantro, Lumpia Wrappers, Egg, Sweet Chili Sauce", picture: "https://rasamalaysia.com/wp-content/uploads/2019/03/lumpia.jpg", source_url: "https://tasty.co/recipe/homemade-lumpia")
# Recipe.create(user_id: User.last.id, title: "Shrimp Summer Rolls", ingredients: "Rice Paper Wrappers, Carrot, Cucumber, Cabbage, Cilantro, Shrimp, Vermecelli",  picture: "https://cdn.sallysbakingaddiction.com/wp-content/uploads/2015/04/How-to-Make-Summer-Rolls.jpg", source_url: "https://www.blueapron.com/recipes/shrimp-summer-rolls-with-peanut-dipping-sauce")
# Recipe.create(user_id: User.last.id, title: "White Claw", ingredients: "Tequila, Vodka, Flavored-Seltzer", picture: "https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1687,w_3000,x_0,y_0/dpr_1.5/c_limit,w_3000/fl_lossy,q_auto/v1568084167/190910-food-drink-white-claw-hero_du5al9", source_url: "https://www.thedailybeast.com/how-the-hell-is-white-claw-hard-seltzer-outselling-budweiser")
# Recipe.create(user_id: User.last.id, title: "Beef Pho", ingredients: "Onion, ginger, Beef Shin, Oxtail, Beef Chuck, Beef Brisket, Star Anise, Cinnamon Stick, Fennel Seeds, Cloves, Coriander, Fish Sauce, Yellow Rock Sugar, Pho Noodles, Pho Toppings",  picture: "https://www.seriouseats.com/recipes/images/2012/06/20120629-pho-food-lab-19.jpg", source_url: "https://www.seriouseats.com/recipes/2012/09/traditional-beef-pho-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Hujiao Bing", ingredients: "Bread Flour, Instant Yeast, Salt, Sugar, Lard, Ground Pork, White Pepper, Szechuan Peppercorn, Soy Sauce, Sugar, Sesame oil, Corn Starch, Scallion", picture: "https://whattocooktoday.com/wp-content/uploads/2015/11/hu-jiao-bing-23.jpg", source_url: "https://whattocooktoday.com/hu-jiao-bing.html")
# Recipe.create(user_id: User.last.id, title: "Cold Cut Banh Mi", ingredients: "French Baguette, Carrot, Daikon, White Wine Vinegar, Pate, Mayonnaise, Cucumber, Cilantro, Cold Cuts, Chili Peppers", picture: "https://www.happyfoodstube.com/wp-content/uploads/2018/08/vietnamese-sandwich-banh-mi-picture.jpg", source_url: "https://www.happyfoodstube.com/vietnamese-sandwich-banh-mi/")
# Recipe.create(user_id: User.last.id, title: "Kalbi", ingredients: "Onion, Asian Pear, Garlic, Soy Sauce, Brown Sugar, Mirin, Scallion, Sesame Oil, Beef Short Rib", picture: "https://www.seriouseats.com/2019/07/20190619-korean-bbq-kalbi-beef-short-ribs-vicky-wasik-21.jpg", source_url: "https://www.seriouseats.com/recipes/2019/08/grilled-beef-galbi-korean-style-marinated-short-ribs.html")
# Recipe.create(user_id: User.last.id, title: "Bulgogi", ingredients: "Soy Sauce, Sugar, Sesame Oil, Mirin, Onion, Garlic, Ginger, Sesame Seed, Rib Eye, Lettuce, White Rice, Kimchi, Hot Bean Paste", picture: "", source_url: "https://www.seriouseats.com/recipes/2009/03/korean-barbeuce-beef-bulgogi-short-rib-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Kimchi Fried Rice", ingredients: "White Rice, Kimchi, Spam, Onion, Scallion, Garlic, Thai Chili, Fish Sauce, Sesame Oil, Cilantro, Eggs", picture: "https://www.seriouseats.com/recipes/images/2016/03/20160403-spam-kimchi-fried-rice-21.jpg", source_url: "https://www.seriouseats.com/recipes/2016/04/kimchi-spam-fried-rice-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Budae Jigae (Army Stew)", ingredients: "Vienna Sausages, Kraft Cheese, rice cakes, Onion, Kimchi, Garlic, Ginger, Shaoxing Wine, Gochujang, White Miso, Soy Sauce, Gochugaru, Silken Tofu, Scallions, Butter", picture: "https://www.seriouseats.com/images/2014/08/20130523-ktown-crawl-pocha-budae-jjigae2-robyn-lee.jpg", source_url: "https://www.seriouseats.com/2014/10/korean-food-types-of-soups-stews-jjigae-guk-tang.html#Budae")
# Recipe.create(user_id: User.last.id, title: "Mochi", ingredients: "Glutinous Rice, Potato Starch, Soybean Flour, Sugar", picture: "https://resize.hswstatic.com/w_796/gif/mochi-1.jpg", source_url: "https://www.justonecookbook.com/how-to-make-mochi-with-a-stand-mixer/")
# Recipe.create(user_id: User.last.id, title: "Guacamole", ingredients: "Lime Juice, Avocado, Salt, Cilantro, Red Onion",  picture: "https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2019/04/Guacamole-10.jpg", source_url: "https://downshiftology.com/recipes/best-ever-guacamole/")
# Recipe.create(user_id: User.last.id, title: "Mochi Waffles", ingredients: "Milk, Egg, Vanilla Extract, Sugar, Baking Powder, Salt",  picture: "https://keepingitrelle.com/wp-content/uploads/2020/02/Mochi-Waffles-13-683x1024.jpg", source_url: "https://keepingitrelle.com/easy-gluten-free-homemade-mochi-waffles/")
# Recipe.create(user_id: User.last.id, title: "Ube Waffles", ingredients: "All Purpose Flour, Cornmeal, Baking Soda, Salt, Buttermilk, Eggs, Canola, Ube Jam, Ube Extract", picture: "https://theunlikelybaker.com/wp-content/uploads/2020/09/Ube-Waffles-Recipe-2.1-776x1024.jpg", source_url: "https://keepingitrelle.com/easy-gluten-free-homemade-mochi-waffles/")
# Recipe.create(user_id: User.last.id, title: "Homemade Boba Tea", ingredients: "Black Tea, Tapioca Pearls, Sugar, Whole Milk", picture: "https://healthynibblesandbits.com/wp-content/uploads/2018/07/How-to-Make-Bubble-Tea-18.jpg", source_url: "https://healthynibblesandbits.com/how-to-make-bubble-tea/")
# Recipe.create(user_id: User.last.id, title: "Chicken Katsu", ingredients: "Chicken, AP Flour, Eggs, Panko, Cabbage, White Rice", picture: "https://therecipecritic.com/wp-content/uploads/2020/01/chickenkatsu.jpg", source_url: "https://www.seriouseats.com/recipes/2017/04/tonkatsu-chicken-pork-katsu-japanese-breaded-cutlets-recipe.html")
# Recipe.create(user_id: User.last.id, title: "Steak Au Poivre", ingredients: "Whole Peppercorns, Cream, Cognac, Butter", picture: "https://www.simplyrecipes.com/wp-content/uploads/2010/04/peppercorn-steak-horiz-a-1600-600x400.jpg", source_url: "https://www.foodnetwork.com/recipes/alton-brown/steak-au-poivre-recipe-1916730")